<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Repository Tugas Pencarian dan Penambangan Web - 4&nbsp; Ringkasan Berita</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./crawl_berita_cnn.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./news_summarization.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Ringkasan Berita</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Repository Tugas Pencarian dan Penambangan Web</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tentang</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./crawl_pta_trunojoyo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Crawl PTA Trunojoyo</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./topic_modeling_pta.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Topic Modeling PTA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./crawl_berita_cnn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Crawl Berita CNN</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./news_summarization.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Ringkasan Berita</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#instalasi" id="toc-instalasi" class="nav-link active" data-scroll-target="#instalasi"><span class="header-section-number">5</span> Instalasi</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data"><span class="header-section-number">6</span> Data</a></li>
  <li><a href="#preprocessing" id="toc-preprocessing" class="nav-link" data-scroll-target="#preprocessing"><span class="header-section-number">7</span> Preprocessing</a></li>
  <li><a href="#ekstraksi-fitur" id="toc-ekstraksi-fitur" class="nav-link" data-scroll-target="#ekstraksi-fitur"><span class="header-section-number">8</span> Ekstraksi Fitur</a>
  <ul class="collapse">
  <li><a href="#tf-idf" id="toc-tf-idf" class="nav-link" data-scroll-target="#tf-idf"><span class="header-section-number">8.1</span> TF-IDF</a></li>
  </ul></li>
  <li><a href="#membentuk-graph" id="toc-membentuk-graph" class="nav-link" data-scroll-target="#membentuk-graph"><span class="header-section-number">9</span> Membentuk Graph</a>
  <ul class="collapse">
  <li><a href="#cosine-similarity" id="toc-cosine-similarity" class="nav-link" data-scroll-target="#cosine-similarity"><span class="header-section-number">9.1</span> Cosine Similarity</a></li>
  <li><a href="#graph" id="toc-graph" class="nav-link" data-scroll-target="#graph"><span class="header-section-number">9.2</span> Graph</a></li>
  </ul></li>
  <li><a href="#matriks-sentralitas" id="toc-matriks-sentralitas" class="nav-link" data-scroll-target="#matriks-sentralitas"><span class="header-section-number">10</span> Matriks Sentralitas</a>
  <ul class="collapse">
  <li><a href="#closeness-centrality" id="toc-closeness-centrality" class="nav-link" data-scroll-target="#closeness-centrality"><span class="header-section-number">10.1</span> Closeness Centrality</a></li>
  <li><a href="#page-rank" id="toc-page-rank" class="nav-link" data-scroll-target="#page-rank"><span class="header-section-number">10.2</span> Page Rank</a></li>
  <li><a href="#eigen-vector" id="toc-eigen-vector" class="nav-link" data-scroll-target="#eigen-vector"><span class="header-section-number">10.3</span> Eigen Vector</a></li>
  </ul></li>
  <li><a href="#evaluasi" id="toc-evaluasi" class="nav-link" data-scroll-target="#evaluasi"><span class="header-section-number">11</span> Evaluasi</a>
  <ul class="collapse">
  <li><a href="#closeness-centrality-1" id="toc-closeness-centrality-1" class="nav-link" data-scroll-target="#closeness-centrality-1"><span class="header-section-number">11.1</span> Closeness Centrality</a></li>
  <li><a href="#page-rank-1" id="toc-page-rank-1" class="nav-link" data-scroll-target="#page-rank-1"><span class="header-section-number">11.2</span> Page Rank</a></li>
  <li><a href="#eigen-vector-1" id="toc-eigen-vector-1" class="nav-link" data-scroll-target="#eigen-vector-1"><span class="header-section-number">11.3</span> Eigen Vector</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Ringkasan Berita</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="instalasi" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Instalasi</h1>
<div class="cell" data-outputid="f4df91b7-cd93-4561-a3e2-2b4eb544473a" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install rouge</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: rouge in /usr/local/lib/python3.10/dist-packages (1.0.1)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from rouge) (1.16.0)</code></pre>
</div>
</div>
<div class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> nltk</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> networkx <span class="im">as</span> nx</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> re</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.feature_extraction.text <span class="im">import</span> TfidfVectorizer</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics.pairwise <span class="im">import</span> cosine_similarity</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> nltk.corpus <span class="im">import</span> stopwords</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> rouge <span class="im">import</span> Rouge</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-outputid="d5dbf201-745f-4f63-dc0f-e283e5b06d21" data-execution_count="3">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>nltk.download(<span class="st">'punkt'</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>nltk.download(<span class="st">"stopwords"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="3">
<pre><code>True</code></pre>
</div>
</div>
</section>
<section id="data" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Data</h1>
<p>Data yang digunakan menggunakan hasil crawling data pada website CNN Indonesia dalam kategori berita nasional.</p>
<div class="cell" data-outputid="53fc52b5-143d-4256-b5ae-1294f3074be6" data-execution_count="4">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> google.colab <span class="im">import</span> drive</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>drive.mount(<span class="st">'/content/drive'</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>csv_path <span class="op">=</span> <span class="st">'/content/drive/My Drive/Task/Pencarian dan Penambangan Web/Tugas 2/data/berita-cnn.csv'</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(csv_path)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="4">

  <div id="df-fe8b72ae-10d2-427a-a32d-3d3c9ccb6e0f" class="colab-df-container">
    <div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">judul</th>
<th data-quarto-table-cell-role="th">berita</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Dirjen Kemendagri Safrizal ZA Jadi Pj Gubernu...</td>
<td>Menteri Dalam Negeri (Mendagri) Tito Karnavian...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Ganjar Temui Gus Mus di Rembang, Bahas Polemi...</td>
<td>Bakal capres PDIP Ganjar Pranowo mengunjungi k...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Nomor Urut Capres-Cawapres Diundi KPU Besok</td>
<td>Komisi Pemilihan Umum (KPU) RI bakal melaksana...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Utut Adianto Pimpin Panja Netralitas TNI di P...</td>
<td>Komisi I DPR sudah menyepakati pembentukan Pan...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Istri Cak Nur Curhat ke Gus Mus: Nepotisme Di...</td>
<td>Sejumlah tokoh bangsa yang mengatasnamakan dir...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>Eks Stafsus SBY Velix Wanggai Jadi Pj Gubernu...</td>
<td>Presiden Joko Widodo menunjuk mantan Staf Khus...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>KPU Resmi Tetapkan Prabowo, Ganjar, Anies seb...</td>
<td>Komisi Pemilihan Umum (KPU) resmi menetapkan t...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>Eks Kadis PUPR Papua Didakwa Terima Suap &amp; Gr...</td>
<td>Kepala Dinas Pekerjaan Umum dan Perumahan Raky...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>Fatia Maulidiyanti Dituntut 3,5 Tahun Penjara...</td>
<td>Aktivitis Hak Asasi Manusia (HAM) Fatia Maulid...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">9</td>
<td>KPK Panggil Keponakan SYL Istri Kapolrestabes...</td>
<td>Komisi Pemberantasan Korupsi (KPK) memanggil k...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">10</td>
<td>Haris Azhar Dituntut 4 Tahun Penjara Kasus Lo...</td>
<td>Aktivitis Hak Asasi Manusia (HAM) Haris Azhar ...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">11</td>
<td>KPK Dalami Dugaan Kartu Anggota Kasino SYL</td>
<td>Komisi Pemberantasan Korupsi (KPK) tengah mend...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">12</td>
<td>Pelecehan Anggota BEM UNY Hoaks, Polisi Tangk...</td>
<td>Polisi memastikan dugaan kasus pelecehan mahas...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">13</td>
<td>Dinkes DKI: Kasus Cacar Monyet di Jakarta Cap...</td>
<td>Dinas Kesehatan (Dinkes) DKI Jakarta melaporka...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">14</td>
<td>Pemkab Ungkap Susun 6 Dimensi pada Perencanaa...</td>
<td>Kabupaten Klaten menyatakan memiliki enam dime...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">15</td>
<td>Sri Mulyani Sebut Petugas Kesehatan Merupakan...</td>
<td>Pemerintah Kabupaten Klaten menggelar Upacara ...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">16</td>
<td>Klaten Ambil Bagian pada Evaluasi Tahap II Sm...</td>
<td>Kabupaten Klaten turut ambil bagian sebagai sa...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">17</td>
<td>Puncak Peringatan HKN Ke-59, Bupati Klaten Ap...</td>
<td>Bupati Klaten, Jawa Tengah, Sri Mulyani, menya...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">18</td>
<td>Nakes Klaten Diminta Jadi Pelopor Budaya Hidu...</td>
<td>Bupati Klaten, Sri Mulyani, meminta tenaga kes...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">19</td>
<td>FOTO: Suhartoyo Resmi Jadi Ketua MK Gantikan ...</td>
<td>Hakim konstitusi Suhartoyo resmi dilantik seba...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">20</td>
<td>Fit and Proper Test Panglima TNI Singgung Isu...</td>
<td>Calon Panglima TNI Jenderal Agus Subiyanto men...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">21</td>
<td>Kapolda Metro Sebut Tersangka Kasus Pemerasan...</td>
<td>Kapolda Metro Jaya Irjen Karyoto menyebut sege...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">22</td>
<td>Irjen Karyoto soal Firli: Kita Lihat Saja Bes...</td>
<td>Kapolda Metro Jaya Irjen Karyoto angkat suara ...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">23</td>
<td>Suhartoyo Janji Segera Bentuk MKMK Permanen</td>
<td>Ketua Mahkamah Konstitusi (MK) Suhartoyo berja...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">24</td>
<td>Mahfud Singgung Menteri Jokowi Ditangkap Koru...</td>
<td>Menko Polhukam Mahfud MD menyinggung banyaknya...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">25</td>
<td>Mahfud Respons Dugaan Saling Sandera KPK-Pold...</td>
<td>Menko Polhukam Mahfud MD angkat suara soal ada...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">26</td>
<td>Agus Subiyanto di DPR: Jika Ingin Damai, Bers...</td>
<td>Kepala Staf Angkatan Darat (KSAD) sekaligus ca...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">27</td>
<td>OTT KPK di Sorong Terkait Pengondisian Temuan...</td>
<td>Komisi Pemberantasan Korupsi (KPK) mengungkapk...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">28</td>
<td>KPK Total Tangkap 5 Orang Terkait OTT di Sorong</td>
<td>Komisi Pemberantasan Korupsi (KPK) total menan...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">29</td>
<td>Anwar Usman Absen di Pelantikan Ketua MK, Izi...</td>
<td>Hakim Konstitusi Anwar Usman tidak hadir dalam...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">30</td>
<td>KPK Total Tangkap 5 Orang Terkait OTT di Sorong</td>
<td>Komisi Pemberantasan Korupsi (KPK) total menan...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">31</td>
<td>Anwar Usman Absen di Pelantikan Ketua MK, Izi...</td>
<td>Hakim Konstitusi Anwar Usman tidak hadir dalam...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">32</td>
<td>Komisi I DPR Sepakati Agus Subiyanto Jadi Pan...</td>
<td>Komisi I DPR secara resmi menyepakati KSAD Jen...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">33</td>
<td>Jelang Penetapan Capres-Cawapres, Jalan Depan...</td>
<td>Jalan Imam Bonjol depan kantor Komisi Pemiliha...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">34</td>
<td>Massa Atribut Serba Hitam Demo di KPU Jelang ...</td>
<td>Demonstrasi terjadi di depan kantor Komisi Pem...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">35</td>
<td>PAN Solid Dukung Prabowo-Gibran dan Menang Pi...</td>
<td>Wakil Bendahara Umum Partai Amanat Nasional (P...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">36</td>
<td>LHKPN Ketua MK Suhartoyo, Punya Harta Rp14,7 ...</td>
<td>Ketua Mahkamah Konstitusi (MK) terpilih pengga...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">37</td>
<td>Fit &amp; Proper Test, Agus Janji Ingatkan Prajur...</td>
<td>Calon Panglima TNI Jenderal Agus Subiyanto ber...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">38</td>
<td>Yasonna soal Wamenkumham Jadi Tersangka: Sila...</td>
<td>Menteri Hukum dan Hak Asasi Manusia (Menkumham...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">39</td>
<td>Ketua MK Suhartoyo Menangis Saat Pidato Soal ...</td>
<td>Hakim Mahkamah Konstitusi (MK) Suhartoyo menan...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">40</td>
<td>Bahlil Heran Gibran Dipersoalkan: Banyak Ment...</td>
<td>Ketua Dewan Pembina Relawan Pengusaha Nasional...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">41</td>
<td>Gibran: Laporkan Saja ke Bawaslu Jika Ada Kec...</td>
<td>Wali Kota Solo sekaligus bakal cawapres Gibran...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">42</td>
<td>Bupati Dhito: Batik Kediri Siap Masuk Kancah ...</td>
<td>Bupati Kediri Hanindhito Himawan Pramana menya...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">43</td>
<td>Sempat Macet Parah, Jalan Mampang Prapatan Ar...</td>
<td>Kemacetan sempat terjadi di Jalan Mampang Prap...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">44</td>
<td>Pejabat Sorong dan Pegawai BPK Terjaring OTT ...</td>
<td>Komisi Pemberantasan Korupsi (KPK) melakukan o...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">45</td>
<td>Fit and Proper Test Calon Panglima TNI, Jende...</td>
<td>Kepala Staf Angkatan Darat (KSAD) sekaligus ca...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">46</td>
<td>VIDEO: Momen Suhartoyo Resmi Dilantik Jadi Ke...</td>
<td>Mahkamah Konstitusi resmi melantik Suhartoyo m...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">47</td>
<td>Wali Kota Semarang Ingin Masyarakat Tak Berga...</td>
<td>Festival pangan pendamping beras bertajuk Prom...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">48</td>
<td>Panglima TNI-Kapolri ke Rumah Agus Subiyanto ...</td>
<td>Panglima TNI Laksamana Yudo Margono dan Kapolr...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">49</td>
<td>Suhartoyo Resmi Jadi Ketua MK Gantikan Anwar ...</td>
<td>Hakim konstitusi Suhartoyo resmi dilantik seba...</td>
</tr>
</tbody>
</table>


</div>
    <div class="colab-df-buttons">

  <div class="colab-df-container">
    <button class="colab-df-convert" onclick="convertToInteractive('df-fe8b72ae-10d2-427a-a32d-3d3c9ccb6e0f')" title="Convert this dataframe to an interactive table." style="display:none;">

  <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewbox="0 -960 960 960">
    <path d="M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z"></path>
  </svg>
    </button>

  <style>
    .colab-df-container {
      display:flex;
      gap: 12px;
    }

    .colab-df-convert {
      background-color: #E8F0FE;
      border: none;
      border-radius: 50%;
      cursor: pointer;
      display: none;
      fill: #1967D2;
      height: 32px;
      padding: 0 0 0 0;
      width: 32px;
    }

    .colab-df-convert:hover {
      background-color: #E2EBFA;
      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);
      fill: #174EA6;
    }

    .colab-df-buttons div {
      margin-bottom: 4px;
    }

    [theme=dark] .colab-df-convert {
      background-color: #3B4455;
      fill: #D2E3FC;
    }

    [theme=dark] .colab-df-convert:hover {
      background-color: #434B5C;
      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);
      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));
      fill: #FFFFFF;
    }
  </style>

    <script>
      const buttonEl =
        document.querySelector('#df-fe8b72ae-10d2-427a-a32d-3d3c9ccb6e0f button.colab-df-convert');
      buttonEl.style.display =
        google.colab.kernel.accessAllowed ? 'block' : 'none';

      async function convertToInteractive(key) {
        const element = document.querySelector('#df-fe8b72ae-10d2-427a-a32d-3d3c9ccb6e0f');
        const dataTable =
          await google.colab.kernel.invokeFunction('convertToInteractive',
                                                    [key], {});
        if (!dataTable) return;

        const docLinkHtml = 'Like what you see? Visit the ' +
          '<a target="_blank" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'
          + ' to learn more about interactive tables.';
        element.innerHTML = '';
        dataTable['output_type'] = 'display_data';
        await google.colab.output.renderOutput(dataTable, element);
        const docLink = document.createElement('div');
        docLink.innerHTML = docLinkHtml;
        element.appendChild(docLink);
      }
    </script>
  </div>


<div id="df-9be8c32f-2e3d-49c0-b5f9-b43ddf53dd8d">
  <button class="colab-df-quickchart" onclick="quickchart('df-9be8c32f-2e3d-49c0-b5f9-b43ddf53dd8d')" title="Suggest charts" style="display:none;">

<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewbox="0 0 24 24" width="24px">
    <g>
        <path d="M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM9 17H7v-7h2v7zm4 0h-2V7h2v10zm4 0h-2v-4h2v4z"></path>
    </g>
</svg>
  </button>

<style>
  .colab-df-quickchart {
      --bg-color: #E8F0FE;
      --fill-color: #1967D2;
      --hover-bg-color: #E2EBFA;
      --hover-fill-color: #174EA6;
      --disabled-fill-color: #AAA;
      --disabled-bg-color: #DDD;
  }

  [theme=dark] .colab-df-quickchart {
      --bg-color: #3B4455;
      --fill-color: #D2E3FC;
      --hover-bg-color: #434B5C;
      --hover-fill-color: #FFFFFF;
      --disabled-bg-color: #3B4455;
      --disabled-fill-color: #666;
  }

  .colab-df-quickchart {
    background-color: var(--bg-color);
    border: none;
    border-radius: 50%;
    cursor: pointer;
    display: none;
    fill: var(--fill-color);
    height: 32px;
    padding: 0;
    width: 32px;
  }

  .colab-df-quickchart:hover {
    background-color: var(--hover-bg-color);
    box-shadow: 0 1px 2px rgba(60, 64, 67, 0.3), 0 1px 3px 1px rgba(60, 64, 67, 0.15);
    fill: var(--button-hover-fill-color);
  }

  .colab-df-quickchart-complete:disabled,
  .colab-df-quickchart-complete:disabled:hover {
    background-color: var(--disabled-bg-color);
    fill: var(--disabled-fill-color);
    box-shadow: none;
  }

  .colab-df-spinner {
    border: 2px solid var(--fill-color);
    border-color: transparent;
    border-bottom-color: var(--fill-color);
    animation:
      spin 1s steps(1) infinite;
  }

  @keyframes spin {
    0% {
      border-color: transparent;
      border-bottom-color: var(--fill-color);
      border-left-color: var(--fill-color);
    }
    20% {
      border-color: transparent;
      border-left-color: var(--fill-color);
      border-top-color: var(--fill-color);
    }
    30% {
      border-color: transparent;
      border-left-color: var(--fill-color);
      border-top-color: var(--fill-color);
      border-right-color: var(--fill-color);
    }
    40% {
      border-color: transparent;
      border-right-color: var(--fill-color);
      border-top-color: var(--fill-color);
    }
    60% {
      border-color: transparent;
      border-right-color: var(--fill-color);
    }
    80% {
      border-color: transparent;
      border-right-color: var(--fill-color);
      border-bottom-color: var(--fill-color);
    }
    90% {
      border-color: transparent;
      border-bottom-color: var(--fill-color);
    }
  }
</style>

  <script>
    async function quickchart(key) {
      const quickchartButtonEl =
        document.querySelector('#' + key + ' button');
      quickchartButtonEl.disabled = true;  // To prevent multiple clicks.
      quickchartButtonEl.classList.add('colab-df-spinner');
      try {
        const charts = await google.colab.kernel.invokeFunction(
            'suggestCharts', [key], {});
      } catch (error) {
        console.error('Error during call to suggestCharts:', error);
      }
      quickchartButtonEl.classList.remove('colab-df-spinner');
      quickchartButtonEl.classList.add('colab-df-quickchart-complete');
    }
    (() => {
      let quickchartButtonEl =
        document.querySelector('#df-9be8c32f-2e3d-49c0-b5f9-b43ddf53dd8d button');
      quickchartButtonEl.style.display =
        google.colab.kernel.accessAllowed ? 'block' : 'none';
    })();
  </script>
</div>
    </div>
  </div>
</div>
</div>
<p>Untuk meringkas suatu dokumen, maka kita hanya memerlukan satu sampel berita yang akan digunakan dengan menggunakan berita pertama</p>
<div class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>berita <span class="op">=</span> df[<span class="st">'berita'</span>].iloc[<span class="dv">0</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="preprocessing" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Preprocessing</h1>
<p>Pada analisis ringkasan dokumen kali ini akan menggunakan 2 metode pengujian, pengujian pertama akan dilakukan langkah ringkasan berita tanpa menggunakan preprocessing dan tahapan pengujian kedua berita yang diringkas akan menggunakan tahapan preprocessing. Tahapan preprocessing ini antara lain yaitu menghapus angka, simbol dan stopword pada berita.</p>
<div class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> preprocessing(text):</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    text <span class="op">=</span> re.sub(<span class="vs">r'\d+'</span>, <span class="st">''</span>, text)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    text <span class="op">=</span> re.sub(<span class="vs">r'[^\w\s.]'</span>, <span class="st">''</span>, text)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    text <span class="op">=</span> text.lower()</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    stop_words <span class="op">=</span> <span class="bu">set</span>(stopwords.words(<span class="st">'indonesian'</span>))</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    words <span class="op">=</span> text.split()</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    filtered_words <span class="op">=</span> [word <span class="cf">for</span> word <span class="kw">in</span> words <span class="cf">if</span> word.lower() <span class="kw">not</span> <span class="kw">in</span> stop_words]</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    preprocessing_text <span class="op">=</span> <span class="st">' '</span>.join(filtered_words)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> preprocessing_text</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>kalimat_preprocessing <span class="op">=</span> preprocessing(berita)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="ekstraksi-fitur" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Ekstraksi Fitur</h1>
<p>Ekstraksi fitur pada tahapan ini menggunakan TF-IDF untuk membentuk vektor pada setiap kalimatnya, sedangkan fitur yang akan digunakan pada vektor TF-IDF ini meliputi <em>term</em> pada keseluruhan dokumen.</p>
<div class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>kalimat <span class="op">=</span> nltk.sent_tokenize(berita) <span class="co">#memecah dokumen berdasarkan kalimatnya tanpa preprocessing</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>kalimat_preprocessing <span class="op">=</span> nltk.sent_tokenize(kalimat_preprocessing) <span class="co">#memecah dokumen berdasarkan kalimatnya menggunakan preprocessing</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="tf-idf" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="tf-idf"><span class="header-section-number">8.1</span> TF-IDF</h2>
<p><em>Term Frequency-Inverse Document Frequency</em> (TF-IDF) adalah vektor yang digunakan untuk mengevaluasi pentingnya kata-kata dalam sebuah dokumen. Nilai frekuensi kemunculan kata dalam setiap dokumen ini menunjukkan seberapa penting kata tersebut dalam dokumen. Berikut merupakan rumus untuk menghitung TF-IDF: <br><br></p>
<p><span class="math display">\[W_{d,t} = tf_{t,d} \cdot idf_{t,d}\]</span> <br><br> Keterangan = <br> <span class="math inline">\(W_{d,t}\)</span> = Nilai T<em>erm Frequency</em> untuk <em>term</em> (t) dalam dokumen (d). <br> <span class="math inline">\(tf_{t,d}\)</span> = Frekuensi kemunculan <em>term </em>(t) dalam dokumen (d). <br> <span class="math inline">\(idf_{t,d}\)</span> = Inverse Document Frequency Nilai kebalikan frekuensi dokumen <em>term</em> (t) dalam dokumen (d).<br><br> Pada dasarnya TF-IDF adalah gabungan dari <em>Term Frequency</em> (TF) dan <em>Inverse Document Frequency</em> (IDF) sehingga sebelum kita membentuk nilai TFIDF, maka kita harus menghitung kedua nilai tersebut. <em>Term Frequency</em> (TF) merupakan perhitungan yang digunakan untuk menentukan seberapa sering kata-kata muncul dalam sebuah dokumen.<br><br> <span class="math display">\[tf= \frac{tf}{max(tf)}\]</span> <br><br> Keterangan = <br> <span class="math inline">\(tf\)</span> = banyaknya kata yang dicari dalam dokumen <br> <span class="math inline">\(max⁡(tf)\)</span> = jumlah kemunculan term terbanyak pada dokumen yang sama <br><br></p>
<p>Sedangkan <em>Inverse Document Frequency</em> (IDF) menilai kata-kata yang sering muncul sebagai kurang signifikan karena kemunculannya dalam banyak dokumen. Semakin rendah nilai IDF, maka kata tersebut akan dianggap kurang berarti dan sebaliknya, semakin tinggi nilai IDF maka kata tersebut akan dianggap lebih relevan atau penting dalam dokumen tersebut. <br><br> <span class="math display">\[idf_{t}= \frac{D}{max(df_{t})}\]</span> <br><br> Keterangan = <br> <span class="math inline">\(D\)</span> = total dokumen <br> <span class="math inline">\(df⁡(t)\)</span> = jumlah dokumen yang mengandung <em>term</em> (t) <br><br></p>
<p>TF-IDF Tanpa Preprocessing</p>
<div class="cell" data-outputid="ca8b09e2-a2bc-4699-e4c5-dba04f6f2ea0" data-execution_count="10">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>tfidf_vectorizer <span class="op">=</span> TfidfVectorizer()</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>tfidf <span class="op">=</span> tfidf_vectorizer.fit_transform(kalimat)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>terms <span class="op">=</span> tfidf_vectorizer.get_feature_names_out()</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>tfidf <span class="op">=</span> pd.DataFrame(data<span class="op">=</span>tfidf.toarray(), columns<span class="op">=</span>terms)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>tfidf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="10">

  <div id="df-f1c95136-dc39-48bd-a7ac-15f6b0184049" class="colab-df-container">
    <div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">11</th>
<th data-quarto-table-cell-role="th">13</th>
<th data-quarto-table-cell-role="th">19</th>
<th data-quarto-table-cell-role="th">2024</th>
<th data-quarto-table-cell-role="th">adalah</th>
<th data-quarto-table-cell-role="th">administrasi</th>
<th data-quarto-table-cell-role="th">adwil</th>
<th data-quarto-table-cell-role="th">akan</th>
<th data-quarto-table-cell-role="th">awasi</th>
<th data-quarto-table-cell-role="th">bangka</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">velix</th>
<th data-quarto-table-cell-role="th">vernando</th>
<th data-quarto-table-cell-role="th">video</th>
<th data-quarto-table-cell-role="th">wakil</th>
<th data-quarto-table-cell-role="th">wali</th>
<th data-quarto-table-cell-role="th">wanggai</th>
<th data-quarto-table-cell-role="th">wawasan</th>
<th data-quarto-table-cell-role="th">wilayah</th>
<th data-quarto-table-cell-role="th">yang</th>
<th data-quarto-table-cell-role="th">za</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.262213</td>
<td>...</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.00000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.300296</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>0.269719</td>
<td>0.269719</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.00000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>0.225098</td>
<td>0.315524</td>
<td>0.000000</td>
<td>0.00000</td>
<td>0.000000</td>
<td>0.275510</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.162701</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.207738</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.00000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.415477</td>
<td>0.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>0.255375</td>
<td>0.255375</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.00000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.00000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.00000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.314751</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.232083</td>
<td>...</td>
<td>0.189617</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.00000</td>
<td>0.000000</td>
<td>0.232083</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>0.261304</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.00000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">9</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.312276</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.00000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">10</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.00000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">11</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.00000</td>
<td>0.178791</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">12</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.194693</td>
<td>0.248586</td>
<td>0.248586</td>
<td>0.000000</td>
<td>0.248586</td>
<td>0.000000</td>
<td>...</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.00000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">13</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.279549</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.00000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">14</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.279706</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>0.254781</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.31184</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">15</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.23924</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.273986</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">16</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.447214</td>
<td>0.00000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
</tbody>
</table>


<p>17 rows × 172 columns</p>
</div>
    <div class="colab-df-buttons">

  <div class="colab-df-container">
    <button class="colab-df-convert" onclick="convertToInteractive('df-f1c95136-dc39-48bd-a7ac-15f6b0184049')" title="Convert this dataframe to an interactive table." style="display:none;">

  <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewbox="0 -960 960 960">
    <path d="M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z"></path>
  </svg>
    </button>

  <style>
    .colab-df-container {
      display:flex;
      gap: 12px;
    }

    .colab-df-convert {
      background-color: #E8F0FE;
      border: none;
      border-radius: 50%;
      cursor: pointer;
      display: none;
      fill: #1967D2;
      height: 32px;
      padding: 0 0 0 0;
      width: 32px;
    }

    .colab-df-convert:hover {
      background-color: #E2EBFA;
      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);
      fill: #174EA6;
    }

    .colab-df-buttons div {
      margin-bottom: 4px;
    }

    [theme=dark] .colab-df-convert {
      background-color: #3B4455;
      fill: #D2E3FC;
    }

    [theme=dark] .colab-df-convert:hover {
      background-color: #434B5C;
      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);
      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));
      fill: #FFFFFF;
    }
  </style>

    <script>
      const buttonEl =
        document.querySelector('#df-f1c95136-dc39-48bd-a7ac-15f6b0184049 button.colab-df-convert');
      buttonEl.style.display =
        google.colab.kernel.accessAllowed ? 'block' : 'none';

      async function convertToInteractive(key) {
        const element = document.querySelector('#df-f1c95136-dc39-48bd-a7ac-15f6b0184049');
        const dataTable =
          await google.colab.kernel.invokeFunction('convertToInteractive',
                                                    [key], {});
        if (!dataTable) return;

        const docLinkHtml = 'Like what you see? Visit the ' +
          '<a target="_blank" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'
          + ' to learn more about interactive tables.';
        element.innerHTML = '';
        dataTable['output_type'] = 'display_data';
        await google.colab.output.renderOutput(dataTable, element);
        const docLink = document.createElement('div');
        docLink.innerHTML = docLinkHtml;
        element.appendChild(docLink);
      }
    </script>
  </div>


<div id="df-7115eaff-55c7-4c7a-81df-4bd6112fe010">
  <button class="colab-df-quickchart" onclick="quickchart('df-7115eaff-55c7-4c7a-81df-4bd6112fe010')" title="Suggest charts" style="display:none;">

<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewbox="0 0 24 24" width="24px">
    <g>
        <path d="M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM9 17H7v-7h2v7zm4 0h-2V7h2v10zm4 0h-2v-4h2v4z"></path>
    </g>
</svg>
  </button>

<style>
  .colab-df-quickchart {
      --bg-color: #E8F0FE;
      --fill-color: #1967D2;
      --hover-bg-color: #E2EBFA;
      --hover-fill-color: #174EA6;
      --disabled-fill-color: #AAA;
      --disabled-bg-color: #DDD;
  }

  [theme=dark] .colab-df-quickchart {
      --bg-color: #3B4455;
      --fill-color: #D2E3FC;
      --hover-bg-color: #434B5C;
      --hover-fill-color: #FFFFFF;
      --disabled-bg-color: #3B4455;
      --disabled-fill-color: #666;
  }

  .colab-df-quickchart {
    background-color: var(--bg-color);
    border: none;
    border-radius: 50%;
    cursor: pointer;
    display: none;
    fill: var(--fill-color);
    height: 32px;
    padding: 0;
    width: 32px;
  }

  .colab-df-quickchart:hover {
    background-color: var(--hover-bg-color);
    box-shadow: 0 1px 2px rgba(60, 64, 67, 0.3), 0 1px 3px 1px rgba(60, 64, 67, 0.15);
    fill: var(--button-hover-fill-color);
  }

  .colab-df-quickchart-complete:disabled,
  .colab-df-quickchart-complete:disabled:hover {
    background-color: var(--disabled-bg-color);
    fill: var(--disabled-fill-color);
    box-shadow: none;
  }

  .colab-df-spinner {
    border: 2px solid var(--fill-color);
    border-color: transparent;
    border-bottom-color: var(--fill-color);
    animation:
      spin 1s steps(1) infinite;
  }

  @keyframes spin {
    0% {
      border-color: transparent;
      border-bottom-color: var(--fill-color);
      border-left-color: var(--fill-color);
    }
    20% {
      border-color: transparent;
      border-left-color: var(--fill-color);
      border-top-color: var(--fill-color);
    }
    30% {
      border-color: transparent;
      border-left-color: var(--fill-color);
      border-top-color: var(--fill-color);
      border-right-color: var(--fill-color);
    }
    40% {
      border-color: transparent;
      border-right-color: var(--fill-color);
      border-top-color: var(--fill-color);
    }
    60% {
      border-color: transparent;
      border-right-color: var(--fill-color);
    }
    80% {
      border-color: transparent;
      border-right-color: var(--fill-color);
      border-bottom-color: var(--fill-color);
    }
    90% {
      border-color: transparent;
      border-bottom-color: var(--fill-color);
    }
  }
</style>

  <script>
    async function quickchart(key) {
      const quickchartButtonEl =
        document.querySelector('#' + key + ' button');
      quickchartButtonEl.disabled = true;  // To prevent multiple clicks.
      quickchartButtonEl.classList.add('colab-df-spinner');
      try {
        const charts = await google.colab.kernel.invokeFunction(
            'suggestCharts', [key], {});
      } catch (error) {
        console.error('Error during call to suggestCharts:', error);
      }
      quickchartButtonEl.classList.remove('colab-df-spinner');
      quickchartButtonEl.classList.add('colab-df-quickchart-complete');
    }
    (() => {
      let quickchartButtonEl =
        document.querySelector('#df-7115eaff-55c7-4c7a-81df-4bd6112fe010 button');
      quickchartButtonEl.style.display =
        google.colab.kernel.accessAllowed ? 'block' : 'none';
    })();
  </script>
</div>
    </div>
  </div>
</div>
</div>
<p>TF-IDF Menggunakan Preprocessing</p>
<div class="cell" data-outputid="c0fb2f6c-0450-4697-e6bb-59396ac79f34" data-execution_count="11">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>tfidf_vectorizer <span class="op">=</span> TfidfVectorizer()</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>tfidf_preprocessing <span class="op">=</span> tfidf_vectorizer.fit_transform(kalimat_preprocessing)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>terms <span class="op">=</span> tfidf_vectorizer.get_feature_names_out()</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>tfidf_preprocessing <span class="op">=</span> pd.DataFrame(data<span class="op">=</span>tfidf_preprocessing.toarray(), columns<span class="op">=</span>terms)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>tfidf_preprocessing</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="11">

  <div id="df-f5b4dc63-7819-4275-818f-c2a1f8e21ed2" class="colab-df-container">
    <div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">administrasi</th>
<th data-quarto-table-cell-role="th">adwil</th>
<th data-quarto-table-cell-role="th">awasi</th>
<th data-quarto-table-cell-role="th">bangka</th>
<th data-quarto-table-cell-role="th">bapakbapak</th>
<th data-quarto-table-cell-role="th">belitung</th>
<th data-quarto-table-cell-role="th">berharap</th>
<th data-quarto-table-cell-role="th">berjalan</th>
<th data-quarto-table-cell-role="th">berperan</th>
<th data-quarto-table-cell-role="th">bersamaan</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">tolong</th>
<th data-quarto-table-cell-role="th">tugas</th>
<th data-quarto-table-cell-role="th">velix</th>
<th data-quarto-table-cell-role="th">vernando</th>
<th data-quarto-table-cell-role="th">wakil</th>
<th data-quarto-table-cell-role="th">wali</th>
<th data-quarto-table-cell-role="th">wanggai</th>
<th data-quarto-table-cell-role="th">wawasan</th>
<th data-quarto-table-cell-role="th">wilayah</th>
<th data-quarto-table-cell-role="th">za</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.294052</td>
<td>0.0000</td>
<td>0.294052</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.336759</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.387236</td>
<td>...</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.276258</td>
<td>0.387236</td>
<td>0.000000</td>
<td>0.0000</td>
<td>0.338128</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.308065</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>0.0000</td>
<td>0.308065</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.380838</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.515543</td>
<td>0.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.260917</td>
<td>0.0000</td>
<td>0.260917</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.213175</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0000</td>
<td>0.260917</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>0.0000</td>
<td>0.411704</td>
<td>0.336372</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">9</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">10</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">11</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.2477</td>
<td>0.000000</td>
<td>0.216287</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>0.2477</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.2477</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">12</td>
<td>0.261989</td>
<td>0.261989</td>
<td>0.261989</td>
<td>0.000000</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">13</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.358922</td>
<td>0.000000</td>
<td>...</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">14</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.317972</td>
<td>0.000000</td>
<td>0.389184</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">15</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.251545</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.288078</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">16</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
</tbody>
</table>


<p>17 rows × 121 columns</p>
</div>
    <div class="colab-df-buttons">

  <div class="colab-df-container">
    <button class="colab-df-convert" onclick="convertToInteractive('df-f5b4dc63-7819-4275-818f-c2a1f8e21ed2')" title="Convert this dataframe to an interactive table." style="display:none;">

  <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewbox="0 -960 960 960">
    <path d="M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z"></path>
  </svg>
    </button>

  <style>
    .colab-df-container {
      display:flex;
      gap: 12px;
    }

    .colab-df-convert {
      background-color: #E8F0FE;
      border: none;
      border-radius: 50%;
      cursor: pointer;
      display: none;
      fill: #1967D2;
      height: 32px;
      padding: 0 0 0 0;
      width: 32px;
    }

    .colab-df-convert:hover {
      background-color: #E2EBFA;
      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);
      fill: #174EA6;
    }

    .colab-df-buttons div {
      margin-bottom: 4px;
    }

    [theme=dark] .colab-df-convert {
      background-color: #3B4455;
      fill: #D2E3FC;
    }

    [theme=dark] .colab-df-convert:hover {
      background-color: #434B5C;
      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);
      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));
      fill: #FFFFFF;
    }
  </style>

    <script>
      const buttonEl =
        document.querySelector('#df-f5b4dc63-7819-4275-818f-c2a1f8e21ed2 button.colab-df-convert');
      buttonEl.style.display =
        google.colab.kernel.accessAllowed ? 'block' : 'none';

      async function convertToInteractive(key) {
        const element = document.querySelector('#df-f5b4dc63-7819-4275-818f-c2a1f8e21ed2');
        const dataTable =
          await google.colab.kernel.invokeFunction('convertToInteractive',
                                                    [key], {});
        if (!dataTable) return;

        const docLinkHtml = 'Like what you see? Visit the ' +
          '<a target="_blank" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'
          + ' to learn more about interactive tables.';
        element.innerHTML = '';
        dataTable['output_type'] = 'display_data';
        await google.colab.output.renderOutput(dataTable, element);
        const docLink = document.createElement('div');
        docLink.innerHTML = docLinkHtml;
        element.appendChild(docLink);
      }
    </script>
  </div>


<div id="df-ea30d828-d04c-4af5-b6e6-51455373b1e2">
  <button class="colab-df-quickchart" onclick="quickchart('df-ea30d828-d04c-4af5-b6e6-51455373b1e2')" title="Suggest charts" style="display:none;">

<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewbox="0 0 24 24" width="24px">
    <g>
        <path d="M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM9 17H7v-7h2v7zm4 0h-2V7h2v10zm4 0h-2v-4h2v4z"></path>
    </g>
</svg>
  </button>

<style>
  .colab-df-quickchart {
      --bg-color: #E8F0FE;
      --fill-color: #1967D2;
      --hover-bg-color: #E2EBFA;
      --hover-fill-color: #174EA6;
      --disabled-fill-color: #AAA;
      --disabled-bg-color: #DDD;
  }

  [theme=dark] .colab-df-quickchart {
      --bg-color: #3B4455;
      --fill-color: #D2E3FC;
      --hover-bg-color: #434B5C;
      --hover-fill-color: #FFFFFF;
      --disabled-bg-color: #3B4455;
      --disabled-fill-color: #666;
  }

  .colab-df-quickchart {
    background-color: var(--bg-color);
    border: none;
    border-radius: 50%;
    cursor: pointer;
    display: none;
    fill: var(--fill-color);
    height: 32px;
    padding: 0;
    width: 32px;
  }

  .colab-df-quickchart:hover {
    background-color: var(--hover-bg-color);
    box-shadow: 0 1px 2px rgba(60, 64, 67, 0.3), 0 1px 3px 1px rgba(60, 64, 67, 0.15);
    fill: var(--button-hover-fill-color);
  }

  .colab-df-quickchart-complete:disabled,
  .colab-df-quickchart-complete:disabled:hover {
    background-color: var(--disabled-bg-color);
    fill: var(--disabled-fill-color);
    box-shadow: none;
  }

  .colab-df-spinner {
    border: 2px solid var(--fill-color);
    border-color: transparent;
    border-bottom-color: var(--fill-color);
    animation:
      spin 1s steps(1) infinite;
  }

  @keyframes spin {
    0% {
      border-color: transparent;
      border-bottom-color: var(--fill-color);
      border-left-color: var(--fill-color);
    }
    20% {
      border-color: transparent;
      border-left-color: var(--fill-color);
      border-top-color: var(--fill-color);
    }
    30% {
      border-color: transparent;
      border-left-color: var(--fill-color);
      border-top-color: var(--fill-color);
      border-right-color: var(--fill-color);
    }
    40% {
      border-color: transparent;
      border-right-color: var(--fill-color);
      border-top-color: var(--fill-color);
    }
    60% {
      border-color: transparent;
      border-right-color: var(--fill-color);
    }
    80% {
      border-color: transparent;
      border-right-color: var(--fill-color);
      border-bottom-color: var(--fill-color);
    }
    90% {
      border-color: transparent;
      border-bottom-color: var(--fill-color);
    }
  }
</style>

  <script>
    async function quickchart(key) {
      const quickchartButtonEl =
        document.querySelector('#' + key + ' button');
      quickchartButtonEl.disabled = true;  // To prevent multiple clicks.
      quickchartButtonEl.classList.add('colab-df-spinner');
      try {
        const charts = await google.colab.kernel.invokeFunction(
            'suggestCharts', [key], {});
      } catch (error) {
        console.error('Error during call to suggestCharts:', error);
      }
      quickchartButtonEl.classList.remove('colab-df-spinner');
      quickchartButtonEl.classList.add('colab-df-quickchart-complete');
    }
    (() => {
      let quickchartButtonEl =
        document.querySelector('#df-ea30d828-d04c-4af5-b6e6-51455373b1e2 button');
      quickchartButtonEl.style.display =
        google.colab.kernel.accessAllowed ? 'block' : 'none';
    })();
  </script>
</div>
    </div>
  </div>
</div>
</div>
</section>
</section>
<section id="membentuk-graph" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Membentuk Graph</h1>
<p>Dalam meringkas dokumen ini diperlukan untuk membentuk graph sebagai gambaran antara kedekatan pada masing-masing kalimat, sehingga dalam ringkasan dokumen yang dihasilkan akan memunculkan kalimat-kalimat penting dan memiliki kedekatan di setiap dokumennya.</p>
<section id="cosine-similarity" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="cosine-similarity"><span class="header-section-number">9.1</span> Cosine Similarity</h2>
<p><em>Cosine similarity</em> digunakan untuk mengukur seberapa mirip dua vektor dalam ruang berdimensi banyak. Hasil dari <em>cosine similarity</em> ini akan menentukan apakah vektor tersebut menuju ke arah yang sama. Semakin kecil sudut antara dua vektor, maka semakin mirip satu sama lain sedangkan begitu juga sebaliknya, semakin besar nilai <em>cosine similarity</em> maka vektor tersebut dianggap jauh kemiripannya. Dalam ringkasan dokumen ini penting untuk menghitung nilai <em>cosine similarity</em> untuk mengetahui hubungan kesamaan antara kalimat satu dengan kalimat lainnya. Vektor yang digunakan untuk menghitung nilai <em>cosine simmilarity</em> ini adalah hasil dari TF-IDF pada langkah sebelumnya. Berikut merupakan rumus yang digunakan untuk menghitung nilai <em>cosine simmilarity</em>.<br><br> <span class="math display">\[simmilarity(A, B) = \frac{A \cdot B}{|A||B|}\]</span> <br><br></p>
<p>Keterangan = <br> A.B = Vector dot product dari A dan B dihitung dengan <span class="math inline">\(\sum_{i=1}^n x_{k}y_{k}\)</span> <br> |A| = Panjang vektor A dihitung dengan <span class="math inline">\(\sum_{i=1}^n x_{k}^2\)</span> <br> |B| = Panjang vektor A dihitung dengan <span class="math inline">\(\sum_{i=1}^n y_{k}^2\)</span> <br></p>
<p>Cosine Similarity Tanpa Preprocessing</p>
<div class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>cosine <span class="op">=</span> cosine_similarity(tfidf, tfidf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-outputid="f371b3f2-2862-47d3-fe77-aa19bea4a188" data-execution_count="13">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>similarity <span class="op">=</span> pd.DataFrame(cosine, columns<span class="op">=</span><span class="bu">range</span>(<span class="bu">len</span>(kalimat)), index<span class="op">=</span><span class="bu">range</span>(<span class="bu">len</span>(kalimat)))</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>similarity</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="13">

  <div id="df-04f63862-11e3-4fec-928f-3c0b5930b982" class="colab-df-container">
    <div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">0</th>
<th data-quarto-table-cell-role="th">1</th>
<th data-quarto-table-cell-role="th">2</th>
<th data-quarto-table-cell-role="th">3</th>
<th data-quarto-table-cell-role="th">4</th>
<th data-quarto-table-cell-role="th">5</th>
<th data-quarto-table-cell-role="th">6</th>
<th data-quarto-table-cell-role="th">7</th>
<th data-quarto-table-cell-role="th">8</th>
<th data-quarto-table-cell-role="th">9</th>
<th data-quarto-table-cell-role="th">10</th>
<th data-quarto-table-cell-role="th">11</th>
<th data-quarto-table-cell-role="th">12</th>
<th data-quarto-table-cell-role="th">13</th>
<th data-quarto-table-cell-role="th">14</th>
<th data-quarto-table-cell-role="th">15</th>
<th data-quarto-table-cell-role="th">16</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1.000000</td>
<td>0.000000</td>
<td>0.183156</td>
<td>0.031750</td>
<td>0.077184</td>
<td>0.106877</td>
<td>0.000000</td>
<td>0.234579</td>
<td>0.000000</td>
<td>0.034685</td>
<td>0.116650</td>
<td>0.067043</td>
<td>0.077952</td>
<td>0.042725</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>0.000000</td>
<td>1.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.206638</td>
<td>0.000000</td>
<td>0.041888</td>
<td>0.035372</td>
<td>0.048745</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.058545</td>
<td>0.000000</td>
<td>0.047528</td>
<td>0.000000</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>0.183156</td>
<td>0.000000</td>
<td>1.000000</td>
<td>0.000000</td>
<td>0.034132</td>
<td>0.112296</td>
<td>0.060918</td>
<td>0.276659</td>
<td>0.200600</td>
<td>0.096883</td>
<td>0.032666</td>
<td>0.041731</td>
<td>0.033793</td>
<td>0.000000</td>
<td>0.057351</td>
<td>0.000000</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>0.031750</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.058014</td>
<td>0.000000</td>
<td>0.029594</td>
<td>0.075541</td>
<td>0.031677</td>
<td>0.044278</td>
<td>0.045509</td>
<td>0.000000</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>0.077184</td>
<td>0.206638</td>
<td>0.034132</td>
<td>0.000000</td>
<td>1.000000</td>
<td>0.032889</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.033780</td>
<td>0.041664</td>
<td>0.059209</td>
<td>0.000000</td>
<td>0.041611</td>
<td>0.000000</td>
<td>0.061096</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>0.106877</td>
<td>0.000000</td>
<td>0.112296</td>
<td>0.000000</td>
<td>0.032889</td>
<td>1.000000</td>
<td>0.000000</td>
<td>0.187934</td>
<td>0.000000</td>
<td>0.083440</td>
<td>0.083680</td>
<td>0.101223</td>
<td>0.032563</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.042397</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>0.000000</td>
<td>0.041888</td>
<td>0.060918</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
<td>0.036043</td>
<td>0.049670</td>
<td>0.060291</td>
<td>0.000000</td>
<td>0.171626</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.048430</td>
<td>0.000000</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>0.234579</td>
<td>0.035372</td>
<td>0.276659</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.187934</td>
<td>0.036043</td>
<td>1.000000</td>
<td>0.210924</td>
<td>0.000000</td>
<td>0.027517</td>
<td>0.017577</td>
<td>0.068995</td>
<td>0.000000</td>
<td>0.089207</td>
<td>0.055524</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>0.000000</td>
<td>0.048745</td>
<td>0.200600</td>
<td>0.058014</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.049670</td>
<td>0.210924</td>
<td>1.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.099860</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.222667</td>
<td>0.000000</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">9</td>
<td>0.034685</td>
<td>0.000000</td>
<td>0.096883</td>
<td>0.000000</td>
<td>0.033780</td>
<td>0.083440</td>
<td>0.060291</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
<td>0.000000</td>
<td>0.091636</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.043546</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">10</td>
<td>0.116650</td>
<td>0.000000</td>
<td>0.032666</td>
<td>0.029594</td>
<td>0.041664</td>
<td>0.083680</td>
<td>0.000000</td>
<td>0.027517</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
<td>0.074679</td>
<td>0.000000</td>
<td>0.099484</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">11</td>
<td>0.067043</td>
<td>0.000000</td>
<td>0.041731</td>
<td>0.075541</td>
<td>0.059209</td>
<td>0.101223</td>
<td>0.171626</td>
<td>0.017577</td>
<td>0.099860</td>
<td>0.091636</td>
<td>0.074679</td>
<td>1.000000</td>
<td>0.033887</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.024932</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">12</td>
<td>0.077952</td>
<td>0.058545</td>
<td>0.033793</td>
<td>0.031677</td>
<td>0.000000</td>
<td>0.032563</td>
<td>0.000000</td>
<td>0.068995</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.033887</td>
<td>1.000000</td>
<td>0.000000</td>
<td>0.054457</td>
<td>0.000000</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">13</td>
<td>0.042725</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.044278</td>
<td>0.041611</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.099484</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
<td>0.000000</td>
<td>0.058398</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">14</td>
<td>0.000000</td>
<td>0.047528</td>
<td>0.057351</td>
<td>0.045509</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.048430</td>
<td>0.089207</td>
<td>0.222667</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.054457</td>
<td>0.000000</td>
<td>1.000000</td>
<td>0.149209</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">15</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.061096</td>
<td>0.042397</td>
<td>0.000000</td>
<td>0.055524</td>
<td>0.000000</td>
<td>0.043546</td>
<td>0.000000</td>
<td>0.024932</td>
<td>0.000000</td>
<td>0.058398</td>
<td>0.149209</td>
<td>1.000000</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">16</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.0</td>
</tr>
</tbody>
</table>


</div>
    <div class="colab-df-buttons">

  <div class="colab-df-container">
    <button class="colab-df-convert" onclick="convertToInteractive('df-04f63862-11e3-4fec-928f-3c0b5930b982')" title="Convert this dataframe to an interactive table." style="display:none;">

  <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewbox="0 -960 960 960">
    <path d="M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z"></path>
  </svg>
    </button>

  <style>
    .colab-df-container {
      display:flex;
      gap: 12px;
    }

    .colab-df-convert {
      background-color: #E8F0FE;
      border: none;
      border-radius: 50%;
      cursor: pointer;
      display: none;
      fill: #1967D2;
      height: 32px;
      padding: 0 0 0 0;
      width: 32px;
    }

    .colab-df-convert:hover {
      background-color: #E2EBFA;
      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);
      fill: #174EA6;
    }

    .colab-df-buttons div {
      margin-bottom: 4px;
    }

    [theme=dark] .colab-df-convert {
      background-color: #3B4455;
      fill: #D2E3FC;
    }

    [theme=dark] .colab-df-convert:hover {
      background-color: #434B5C;
      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);
      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));
      fill: #FFFFFF;
    }
  </style>

    <script>
      const buttonEl =
        document.querySelector('#df-04f63862-11e3-4fec-928f-3c0b5930b982 button.colab-df-convert');
      buttonEl.style.display =
        google.colab.kernel.accessAllowed ? 'block' : 'none';

      async function convertToInteractive(key) {
        const element = document.querySelector('#df-04f63862-11e3-4fec-928f-3c0b5930b982');
        const dataTable =
          await google.colab.kernel.invokeFunction('convertToInteractive',
                                                    [key], {});
        if (!dataTable) return;

        const docLinkHtml = 'Like what you see? Visit the ' +
          '<a target="_blank" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'
          + ' to learn more about interactive tables.';
        element.innerHTML = '';
        dataTable['output_type'] = 'display_data';
        await google.colab.output.renderOutput(dataTable, element);
        const docLink = document.createElement('div');
        docLink.innerHTML = docLinkHtml;
        element.appendChild(docLink);
      }
    </script>
  </div>


<div id="df-d994fa8d-8f8b-4b9a-ab72-230fa2b0c580">
  <button class="colab-df-quickchart" onclick="quickchart('df-d994fa8d-8f8b-4b9a-ab72-230fa2b0c580')" title="Suggest charts" style="display:none;">

<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewbox="0 0 24 24" width="24px">
    <g>
        <path d="M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM9 17H7v-7h2v7zm4 0h-2V7h2v10zm4 0h-2v-4h2v4z"></path>
    </g>
</svg>
  </button>

<style>
  .colab-df-quickchart {
      --bg-color: #E8F0FE;
      --fill-color: #1967D2;
      --hover-bg-color: #E2EBFA;
      --hover-fill-color: #174EA6;
      --disabled-fill-color: #AAA;
      --disabled-bg-color: #DDD;
  }

  [theme=dark] .colab-df-quickchart {
      --bg-color: #3B4455;
      --fill-color: #D2E3FC;
      --hover-bg-color: #434B5C;
      --hover-fill-color: #FFFFFF;
      --disabled-bg-color: #3B4455;
      --disabled-fill-color: #666;
  }

  .colab-df-quickchart {
    background-color: var(--bg-color);
    border: none;
    border-radius: 50%;
    cursor: pointer;
    display: none;
    fill: var(--fill-color);
    height: 32px;
    padding: 0;
    width: 32px;
  }

  .colab-df-quickchart:hover {
    background-color: var(--hover-bg-color);
    box-shadow: 0 1px 2px rgba(60, 64, 67, 0.3), 0 1px 3px 1px rgba(60, 64, 67, 0.15);
    fill: var(--button-hover-fill-color);
  }

  .colab-df-quickchart-complete:disabled,
  .colab-df-quickchart-complete:disabled:hover {
    background-color: var(--disabled-bg-color);
    fill: var(--disabled-fill-color);
    box-shadow: none;
  }

  .colab-df-spinner {
    border: 2px solid var(--fill-color);
    border-color: transparent;
    border-bottom-color: var(--fill-color);
    animation:
      spin 1s steps(1) infinite;
  }

  @keyframes spin {
    0% {
      border-color: transparent;
      border-bottom-color: var(--fill-color);
      border-left-color: var(--fill-color);
    }
    20% {
      border-color: transparent;
      border-left-color: var(--fill-color);
      border-top-color: var(--fill-color);
    }
    30% {
      border-color: transparent;
      border-left-color: var(--fill-color);
      border-top-color: var(--fill-color);
      border-right-color: var(--fill-color);
    }
    40% {
      border-color: transparent;
      border-right-color: var(--fill-color);
      border-top-color: var(--fill-color);
    }
    60% {
      border-color: transparent;
      border-right-color: var(--fill-color);
    }
    80% {
      border-color: transparent;
      border-right-color: var(--fill-color);
      border-bottom-color: var(--fill-color);
    }
    90% {
      border-color: transparent;
      border-bottom-color: var(--fill-color);
    }
  }
</style>

  <script>
    async function quickchart(key) {
      const quickchartButtonEl =
        document.querySelector('#' + key + ' button');
      quickchartButtonEl.disabled = true;  // To prevent multiple clicks.
      quickchartButtonEl.classList.add('colab-df-spinner');
      try {
        const charts = await google.colab.kernel.invokeFunction(
            'suggestCharts', [key], {});
      } catch (error) {
        console.error('Error during call to suggestCharts:', error);
      }
      quickchartButtonEl.classList.remove('colab-df-spinner');
      quickchartButtonEl.classList.add('colab-df-quickchart-complete');
    }
    (() => {
      let quickchartButtonEl =
        document.querySelector('#df-d994fa8d-8f8b-4b9a-ab72-230fa2b0c580 button');
      quickchartButtonEl.style.display =
        google.colab.kernel.accessAllowed ? 'block' : 'none';
    })();
  </script>
</div>
    </div>
  </div>
</div>
</div>
<p>Cosine Similarity Menggunakan Preprocessing</p>
<div class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>cosine_preprocessing <span class="op">=</span> cosine_similarity(tfidf_preprocessing, tfidf_preprocessing)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-outputid="09f3b62f-4892-4c4f-e892-ad96f99fe9a1" data-execution_count="15">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>similarity_preprocessing <span class="op">=</span> pd.DataFrame(cosine_preprocessing, columns<span class="op">=</span><span class="bu">range</span>(<span class="bu">len</span>(kalimat)), index<span class="op">=</span><span class="bu">range</span>(<span class="bu">len</span>(kalimat)))</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>similarity_preprocessing</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="15">

  <div id="df-a7d45d16-728c-493b-ae7b-d7e7c3a65f4b" class="colab-df-container">
    <div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">0</th>
<th data-quarto-table-cell-role="th">1</th>
<th data-quarto-table-cell-role="th">2</th>
<th data-quarto-table-cell-role="th">3</th>
<th data-quarto-table-cell-role="th">4</th>
<th data-quarto-table-cell-role="th">5</th>
<th data-quarto-table-cell-role="th">6</th>
<th data-quarto-table-cell-role="th">7</th>
<th data-quarto-table-cell-role="th">8</th>
<th data-quarto-table-cell-role="th">9</th>
<th data-quarto-table-cell-role="th">10</th>
<th data-quarto-table-cell-role="th">11</th>
<th data-quarto-table-cell-role="th">12</th>
<th data-quarto-table-cell-role="th">13</th>
<th data-quarto-table-cell-role="th">14</th>
<th data-quarto-table-cell-role="th">15</th>
<th data-quarto-table-cell-role="th">16</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1.000000</td>
<td>0.000000</td>
<td>0.152651</td>
<td>0.060469</td>
<td>0.047436</td>
<td>0.131893</td>
<td>0.000000</td>
<td>0.295745</td>
<td>0.000000</td>
<td>0.043678</td>
<td>0.112841</td>
<td>0.104161</td>
<td>0.092131</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>0.000000</td>
<td>1.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.105852</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.072819</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>0.152651</td>
<td>0.000000</td>
<td>1.000000</td>
<td>0.000000</td>
<td>0.054547</td>
<td>0.151663</td>
<td>0.000000</td>
<td>0.381721</td>
<td>0.316919</td>
<td>0.050225</td>
<td>0.054610</td>
<td>0.070955</td>
<td>0.043710</td>
<td>0.000000</td>
<td>0.087843</td>
<td>0.000000</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>0.060469</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.126832</td>
<td>0.000000</td>
<td>0.068464</td>
<td>0.111109</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>0.047436</td>
<td>0.105852</td>
<td>0.054547</td>
<td>0.000000</td>
<td>1.000000</td>
<td>0.047130</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.049395</td>
<td>0.000000</td>
<td>0.034891</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.083649</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>0.131893</td>
<td>0.000000</td>
<td>0.151663</td>
<td>0.000000</td>
<td>0.047130</td>
<td>1.000000</td>
<td>0.000000</td>
<td>0.156279</td>
<td>0.000000</td>
<td>0.043396</td>
<td>0.047184</td>
<td>0.061307</td>
<td>0.037766</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.097365</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>0.295745</td>
<td>0.000000</td>
<td>0.381721</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.156279</td>
<td>0.000000</td>
<td>1.000000</td>
<td>0.244551</td>
<td>0.000000</td>
<td>0.042140</td>
<td>0.027376</td>
<td>0.081749</td>
<td>0.000000</td>
<td>0.067784</td>
<td>0.000000</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.316919</td>
<td>0.126832</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.244551</td>
<td>1.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.106957</td>
<td>0.000000</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">9</td>
<td>0.043678</td>
<td>0.000000</td>
<td>0.050225</td>
<td>0.000000</td>
<td>0.049395</td>
<td>0.043396</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
<td>0.000000</td>
<td>0.098353</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">10</td>
<td>0.112841</td>
<td>0.000000</td>
<td>0.054610</td>
<td>0.068464</td>
<td>0.000000</td>
<td>0.047184</td>
<td>0.000000</td>
<td>0.042140</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
<td>0.082999</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">11</td>
<td>0.104161</td>
<td>0.000000</td>
<td>0.070955</td>
<td>0.111109</td>
<td>0.034891</td>
<td>0.061307</td>
<td>0.097365</td>
<td>0.027376</td>
<td>0.000000</td>
<td>0.098353</td>
<td>0.082999</td>
<td>1.000000</td>
<td>0.049479</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">12</td>
<td>0.092131</td>
<td>0.072819</td>
<td>0.043710</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.037766</td>
<td>0.000000</td>
<td>0.081749</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.049479</td>
<td>1.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">13</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
<td>0.000000</td>
<td>0.078835</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">14</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.087843</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.067784</td>
<td>0.106957</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
<td>0.195794</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">15</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.083649</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.078835</td>
<td>0.195794</td>
<td>1.000000</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">16</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.0</td>
</tr>
</tbody>
</table>


</div>
    <div class="colab-df-buttons">

  <div class="colab-df-container">
    <button class="colab-df-convert" onclick="convertToInteractive('df-a7d45d16-728c-493b-ae7b-d7e7c3a65f4b')" title="Convert this dataframe to an interactive table." style="display:none;">

  <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewbox="0 -960 960 960">
    <path d="M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z"></path>
  </svg>
    </button>

  <style>
    .colab-df-container {
      display:flex;
      gap: 12px;
    }

    .colab-df-convert {
      background-color: #E8F0FE;
      border: none;
      border-radius: 50%;
      cursor: pointer;
      display: none;
      fill: #1967D2;
      height: 32px;
      padding: 0 0 0 0;
      width: 32px;
    }

    .colab-df-convert:hover {
      background-color: #E2EBFA;
      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);
      fill: #174EA6;
    }

    .colab-df-buttons div {
      margin-bottom: 4px;
    }

    [theme=dark] .colab-df-convert {
      background-color: #3B4455;
      fill: #D2E3FC;
    }

    [theme=dark] .colab-df-convert:hover {
      background-color: #434B5C;
      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);
      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));
      fill: #FFFFFF;
    }
  </style>

    <script>
      const buttonEl =
        document.querySelector('#df-a7d45d16-728c-493b-ae7b-d7e7c3a65f4b button.colab-df-convert');
      buttonEl.style.display =
        google.colab.kernel.accessAllowed ? 'block' : 'none';

      async function convertToInteractive(key) {
        const element = document.querySelector('#df-a7d45d16-728c-493b-ae7b-d7e7c3a65f4b');
        const dataTable =
          await google.colab.kernel.invokeFunction('convertToInteractive',
                                                    [key], {});
        if (!dataTable) return;

        const docLinkHtml = 'Like what you see? Visit the ' +
          '<a target="_blank" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'
          + ' to learn more about interactive tables.';
        element.innerHTML = '';
        dataTable['output_type'] = 'display_data';
        await google.colab.output.renderOutput(dataTable, element);
        const docLink = document.createElement('div');
        docLink.innerHTML = docLinkHtml;
        element.appendChild(docLink);
      }
    </script>
  </div>


<div id="df-d1e4dcae-5e18-4b77-92d6-fd2efe554f4b">
  <button class="colab-df-quickchart" onclick="quickchart('df-d1e4dcae-5e18-4b77-92d6-fd2efe554f4b')" title="Suggest charts" style="display:none;">

<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewbox="0 0 24 24" width="24px">
    <g>
        <path d="M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM9 17H7v-7h2v7zm4 0h-2V7h2v10zm4 0h-2v-4h2v4z"></path>
    </g>
</svg>
  </button>

<style>
  .colab-df-quickchart {
      --bg-color: #E8F0FE;
      --fill-color: #1967D2;
      --hover-bg-color: #E2EBFA;
      --hover-fill-color: #174EA6;
      --disabled-fill-color: #AAA;
      --disabled-bg-color: #DDD;
  }

  [theme=dark] .colab-df-quickchart {
      --bg-color: #3B4455;
      --fill-color: #D2E3FC;
      --hover-bg-color: #434B5C;
      --hover-fill-color: #FFFFFF;
      --disabled-bg-color: #3B4455;
      --disabled-fill-color: #666;
  }

  .colab-df-quickchart {
    background-color: var(--bg-color);
    border: none;
    border-radius: 50%;
    cursor: pointer;
    display: none;
    fill: var(--fill-color);
    height: 32px;
    padding: 0;
    width: 32px;
  }

  .colab-df-quickchart:hover {
    background-color: var(--hover-bg-color);
    box-shadow: 0 1px 2px rgba(60, 64, 67, 0.3), 0 1px 3px 1px rgba(60, 64, 67, 0.15);
    fill: var(--button-hover-fill-color);
  }

  .colab-df-quickchart-complete:disabled,
  .colab-df-quickchart-complete:disabled:hover {
    background-color: var(--disabled-bg-color);
    fill: var(--disabled-fill-color);
    box-shadow: none;
  }

  .colab-df-spinner {
    border: 2px solid var(--fill-color);
    border-color: transparent;
    border-bottom-color: var(--fill-color);
    animation:
      spin 1s steps(1) infinite;
  }

  @keyframes spin {
    0% {
      border-color: transparent;
      border-bottom-color: var(--fill-color);
      border-left-color: var(--fill-color);
    }
    20% {
      border-color: transparent;
      border-left-color: var(--fill-color);
      border-top-color: var(--fill-color);
    }
    30% {
      border-color: transparent;
      border-left-color: var(--fill-color);
      border-top-color: var(--fill-color);
      border-right-color: var(--fill-color);
    }
    40% {
      border-color: transparent;
      border-right-color: var(--fill-color);
      border-top-color: var(--fill-color);
    }
    60% {
      border-color: transparent;
      border-right-color: var(--fill-color);
    }
    80% {
      border-color: transparent;
      border-right-color: var(--fill-color);
      border-bottom-color: var(--fill-color);
    }
    90% {
      border-color: transparent;
      border-bottom-color: var(--fill-color);
    }
  }
</style>

  <script>
    async function quickchart(key) {
      const quickchartButtonEl =
        document.querySelector('#' + key + ' button');
      quickchartButtonEl.disabled = true;  // To prevent multiple clicks.
      quickchartButtonEl.classList.add('colab-df-spinner');
      try {
        const charts = await google.colab.kernel.invokeFunction(
            'suggestCharts', [key], {});
      } catch (error) {
        console.error('Error during call to suggestCharts:', error);
      }
      quickchartButtonEl.classList.remove('colab-df-spinner');
      quickchartButtonEl.classList.add('colab-df-quickchart-complete');
    }
    (() => {
      let quickchartButtonEl =
        document.querySelector('#df-d1e4dcae-5e18-4b77-92d6-fd2efe554f4b button');
      quickchartButtonEl.style.display =
        google.colab.kernel.accessAllowed ? 'block' : 'none';
    })();
  </script>
</div>
    </div>
  </div>
</div>
</div>
</section>
<section id="graph" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="graph"><span class="header-section-number">9.2</span> Graph</h2>
<p>Hasil dari nilai <em>cosine simmilarity</em> ini akan dapat digunakan untuk membentuk graph dengan menggunakan modul nx.graph. Graph ini akan menggambarkan ilustrasi dari kedekatan setiap kalimatnya dalam berita tersebut. Dalam proses penggambaran graph tersebut diperlukan ambang batas (<em>treshold</em>) yang digunakan untuk memberikan batasan agar keseluruhan kalimatnya tidak dihubungkan menggunakan garis <em>(edge)</em>. Nilai ambang batas (<em>treshold</em>) yang digunakan adalah 0.1</p>
<p>Graph Tanpa Preprocessing</p>
<div class="cell" data-outputid="02dabde0-4596-4211-c2a6-91b5df090073" data-execution_count="16">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>G <span class="op">=</span> nx.DiGraph()</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(cosine)):</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>    G.add_node(i)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(cosine)):</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(cosine)):</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>        similarity <span class="op">=</span> cosine[i][j]</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> similarity <span class="op">&gt;</span> <span class="fl">0.1</span> <span class="kw">and</span> i <span class="op">!=</span> j:</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>            G.add_edge(i, j)</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>pos <span class="op">=</span> nx.spring_layout(G)</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>nx.draw_networkx_nodes(G, pos, node_size<span class="op">=</span><span class="dv">500</span>, node_color<span class="op">=</span><span class="st">'b'</span>)</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>nx.draw_networkx_edges(G, pos, edge_color<span class="op">=</span><span class="st">'red'</span>, arrows<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>nx.draw_networkx_labels(G, pos)</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="news_summarization_files/figure-html/cell-17-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>Graph Menggunakan Preprocessing</p>
<div class="cell" data-outputid="46b146bd-aff8-445b-9aa8-5d17a636f12f" data-execution_count="17">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>G_preprocessing <span class="op">=</span> nx.DiGraph()</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(cosine_preprocessing)):</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>    G_preprocessing.add_node(i)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(cosine_preprocessing)):</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(cosine_preprocessing)):</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>        similarity_preprocessing <span class="op">=</span> cosine_preprocessing[i][j]</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> similarity_preprocessing <span class="op">&gt;</span> <span class="fl">0.1</span> <span class="kw">and</span> i <span class="op">!=</span> j:</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>            G_preprocessing.add_edge(i, j)</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>pos <span class="op">=</span> nx.spring_layout(G)</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>nx.draw_networkx_nodes(G, pos, node_size<span class="op">=</span><span class="dv">500</span>, node_color<span class="op">=</span><span class="st">'b'</span>)</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>nx.draw_networkx_edges(G, pos, edge_color<span class="op">=</span><span class="st">'red'</span>, arrows<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>nx.draw_networkx_labels(G, pos)</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="news_summarization_files/figure-html/cell-18-output-1.png" class="img-fluid"></p>
</div>
</div>
</section>
</section>
<section id="matriks-sentralitas" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Matriks Sentralitas</h1>
<p>Matriks Sentralitas adalah matriks yang digunakan untuk merepresentasikan ukuran sentralitas dari setiap <em>node</em> dalam jaringan. Sentralitas adalah konsep dalam analisis jaringan yang mencoba mengukur sejauh mana suatu <em>node</em> berada di pusat jaringan atau sejauh mana suatu <em>node</em> penting dalam graph. Beberapa matriks ini akan digunakan untuk membangun ringkasan dokumen yang dibuat oleh sistem, matriks ini didapatkan dari bentuk graph yang telah terbentuk pada langkah sebelumnya.</p>
<section id="closeness-centrality" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="closeness-centrality"><span class="header-section-number">10.1</span> Closeness Centrality</h2>
<p><em>Closeness similarity</em> adalah ukuran sejauh mana nilai kedekatan antara pasangan node dalam suatu jaringan serupa. Dengan ini kita dapat mengukur kesamaan struktural antara node-node dalam graf berdasarkan nilai kedekatan mereka. Closeness similarity dirumuskan sebagai berikut.</p>
<p><span class="math display">\[CC(i) = \frac{N-1}{\sum_{j}d(i, j)} \]</span> <br></p>
<p>Keterangan = <br> N = nomor dari masing-masing node <br> <span class="math inline">\(d(i, j)\)</span> = d adalah panjang jalur terpendek antara node i dan j dalam jaringan</p>
<p>Closeness Centrality Tanpa Preprocessing</p>
<div class="cell" data-outputid="fb127432-cccb-4e91-fb5e-6e173de3a281" data-execution_count="18">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>closeness<span class="op">=</span> nx.closeness_centrality(G)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>sorted_closeness <span class="op">=</span> <span class="bu">sorted</span>(closeness.items(), key<span class="op">=</span><span class="kw">lambda</span> x: x[<span class="dv">1</span>], reverse<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Closeness Centrality:"</span>)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> node, closeness <span class="kw">in</span> sorted_closeness:</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Node </span><span class="sc">{</span>node<span class="sc">}</span><span class="ss">: </span><span class="sc">{</span>closeness<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Closeness Centrality:
Node 2: 0.3164
Node 7: 0.3164
Node 5: 0.2978
Node 0: 0.2812
Node 8: 0.2664
Node 11: 0.2201
Node 14: 0.2025
Node 10: 0.1947
Node 6: 0.1633
Node 15: 0.1534
Node 1: 0.0625
Node 4: 0.0625
Node 3: 0.0000
Node 9: 0.0000
Node 12: 0.0000
Node 13: 0.0000
Node 16: 0.0000</code></pre>
</div>
</div>
<div class="cell" data-outputid="51c5a8a3-4c09-4a40-a6cf-09919b9c999d" data-execution_count="19">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>ringkasan_closeness <span class="op">=</span> <span class="st">""</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Tiga Node Tertinggi Closeness Centrality:"</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> node, closeness <span class="kw">in</span> sorted_closeness[:<span class="dv">3</span>]:</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>    top_sentence <span class="op">=</span> kalimat[node]</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>    ringkasan_closeness <span class="op">+=</span> top_sentence <span class="op">+</span> <span class="st">" "</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Node </span><span class="sc">{</span>node<span class="sc">}</span><span class="ss">: Closeness Centrality = </span><span class="sc">{</span>closeness<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Kalimat: </span><span class="sc">{</span>top_sentence<span class="sc">}</span><span class="ch">\n</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Tiga Node Tertinggi Closeness Centrality:
Node 2: Closeness Centrality = 0.3164
Kalimat: Pada saat bersamaan, Tito juga melantik Velix Vernando Wanggai sebagai Pj Gubernur Papua Pegunungan.

Node 7: Closeness Centrality = 0.3164
Kalimat: Eks Stafsus SBY Velix Wanggai Jadi Pj Gubernur Papua Pegunungan Dia meminta Safrizal menangani permasalahan lingkungan di Bangka Belitung.

Node 5: Closeness Centrality = 0.2978
Kalimat: Tito meminta dua pj gubernur menangani kemiskinan ekstrem, inflasi, stunting, infrastruktur, pendidikan, dan kesehatan.
</code></pre>
</div>
</div>
<p>Closeness Centrality Menggunakan Preprocessing</p>
<div class="cell" data-outputid="f78de230-29cc-4010-e85e-a42064b5345f" data-execution_count="20">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>closeness_preprocessing <span class="op">=</span> nx.closeness_centrality(G_preprocessing)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>sorted_closeness_preprocessing <span class="op">=</span> <span class="bu">sorted</span>(closeness_preprocessing.items(), key<span class="op">=</span><span class="kw">lambda</span> x: x[<span class="dv">1</span>], reverse<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Closeness Centrality:"</span>)</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> node, closeness <span class="kw">in</span> sorted_closeness_preprocessing:</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Node </span><span class="sc">{</span>node<span class="sc">}</span><span class="ss">: </span><span class="sc">{</span>closeness<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Closeness Centrality:
Node 2: 0.3375
Node 7: 0.3375
Node 8: 0.3375
Node 0: 0.3164
Node 3: 0.2664
Node 5: 0.2664
Node 11: 0.2664
Node 14: 0.2411
Node 10: 0.2109
Node 15: 0.1746
Node 1: 0.0625
Node 4: 0.0625
Node 6: 0.0000
Node 9: 0.0000
Node 12: 0.0000
Node 13: 0.0000
Node 16: 0.0000</code></pre>
</div>
</div>
<div class="cell" data-outputid="51c2435e-c45d-4e98-9ef0-8eba11a8711a" data-execution_count="21">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>ringkasan_closeness_preprocessing <span class="op">=</span> <span class="st">""</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Tiga Node Tertinggi Closeness Centrality Menggunakan Preprocessing:"</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> node, closeness_preprocessing <span class="kw">in</span> sorted_closeness_preprocessing[:<span class="dv">3</span>]:</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>    top_sentence <span class="op">=</span> kalimat[node]</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    ringkasan_closeness_preprocessing <span class="op">+=</span> top_sentence <span class="op">+</span> <span class="st">" "</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Node </span><span class="sc">{</span>node<span class="sc">}</span><span class="ss">: Closeness Centrality = </span><span class="sc">{</span>closeness_preprocessing<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Kalimat: </span><span class="sc">{</span>top_sentence<span class="sc">}</span><span class="ch">\n</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Tiga Node Tertinggi Closeness Centrality Menggunakan Preprocessing:
Node 2: Closeness Centrality = 0.3375
Kalimat: Pada saat bersamaan, Tito juga melantik Velix Vernando Wanggai sebagai Pj Gubernur Papua Pegunungan.

Node 7: Closeness Centrality = 0.3375
Kalimat: Eks Stafsus SBY Velix Wanggai Jadi Pj Gubernur Papua Pegunungan Dia meminta Safrizal menangani permasalahan lingkungan di Bangka Belitung.

Node 8: Closeness Centrality = 0.3375
Kalimat: Sementara untuk Velix, tugas keamanan di Papua Pegunungan menjadi prioritas.
</code></pre>
</div>
</div>
</section>
<section id="page-rank" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="page-rank"><span class="header-section-number">10.2</span> Page Rank</h2>
<p>Dalam konteks ini, dokumen dianggap sebagai “halaman” yang terhubung oleh hubungan yang merefleksikan keterkaitan atau relevansinya. Dengan menerapkan konsep PageRank, dokumen yang dianggap lebih “penting” atau relevan dapat diberikan skor lebih tinggi. Penggunaan faktor damping, serupa dengan dalam algoritma PageRank, dapat membantu mengontrol sejauh mana pengaruh satu dokumen terhadap yang lain. Dengan memberikan skor pada dokumen berdasarkan hubungan mereka dalam jaringan informasi, kita dapat menghasilkan ringkasan yang mencerminkan tingkat relevansi dan pentingnya masing-masing dokumen dalam konteks keseluruhan. <br><br> <span class="math display">\[S(V_{i}) = (1-d)+d * \sum\frac{1}{Out(V_{j})}S(V_{j})\]</span> <br><br></p>
<p>Keterangan = <br> d = faktor redaman, jika tidak ada sambungan keluar <br> in(Vi) = tautan masuk dari i, yang merupakan satu set <br> out(Vj) = tautan keluar dari j, yang merupakan satu set <br> |out(Vj)| = jumlah tautan keluar</p>
<p>Page Rank Tanpa Preprocessing</p>
<div class="cell" data-outputid="7b9da667-3793-460e-bc4e-a1987c4a4f7b" data-execution_count="22">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>pagerank <span class="op">=</span> nx.pagerank(G)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>sorted_pagerank<span class="op">=</span> <span class="bu">sorted</span>(pagerank.items(), key<span class="op">=</span><span class="kw">lambda</span> x: x[<span class="dv">1</span>], reverse<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Page Rank :"</span>)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> node, pagerank <span class="kw">in</span> sorted_pagerank:</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Node </span><span class="sc">{</span>node<span class="sc">}</span><span class="ss">: </span><span class="sc">{</span>pagerank<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Page Rank :
Node 5: 0.1103
Node 0: 0.1102
Node 2: 0.1061
Node 7: 0.1061
Node 8: 0.0879
Node 1: 0.0784
Node 4: 0.0784
Node 14: 0.0731
Node 11: 0.0708
Node 15: 0.0428
Node 6: 0.0418
Node 10: 0.0352
Node 3: 0.0118
Node 9: 0.0118
Node 12: 0.0118
Node 13: 0.0118
Node 16: 0.0118</code></pre>
</div>
</div>
<div class="cell" data-outputid="25d6a375-b59a-458f-e117-1e91885a8202" data-execution_count="23">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>ringkasan_pagerank <span class="op">=</span> <span class="st">""</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Tiga Node Tertinggi Page Rank :"</span>)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> node, pagerank <span class="kw">in</span> sorted_pagerank[:<span class="dv">3</span>]:</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>    top_sentence <span class="op">=</span> kalimat[node]</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>    ringkasan_pagerank <span class="op">+=</span> top_sentence <span class="op">+</span> <span class="st">" "</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Node </span><span class="sc">{</span>node<span class="sc">}</span><span class="ss">: Page Rank = </span><span class="sc">{</span>pagerank<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Kalimat: </span><span class="sc">{</span>top_sentence<span class="sc">}</span><span class="ch">\n</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Tiga Node Tertinggi Page Rank :
Node 5: Page Rank = 0.1103
Kalimat: Tito meminta dua pj gubernur menangani kemiskinan ekstrem, inflasi, stunting, infrastruktur, pendidikan, dan kesehatan.

Node 0: Page Rank = 0.1102
Kalimat: Menteri Dalam Negeri (Mendagri) Tito Karnavian menunjuk Safrizal ZA sebagai Penjabat (Pj) Gubernur Bangka Belitung.

Node 2: Page Rank = 0.1061
Kalimat: Pada saat bersamaan, Tito juga melantik Velix Vernando Wanggai sebagai Pj Gubernur Papua Pegunungan.
</code></pre>
</div>
</div>
<p>Page Rank Menggunakan Preprocessing</p>
<div class="cell" data-outputid="51f07e91-7dc1-48de-87c1-9a8b868d9dde" data-execution_count="24">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>pagerank_preprocessing <span class="op">=</span> nx.pagerank(G_preprocessing)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>sorted_pagerank_preprocessing<span class="op">=</span> <span class="bu">sorted</span>(pagerank_preprocessing.items(), key<span class="op">=</span><span class="kw">lambda</span> x: x[<span class="dv">1</span>], reverse<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Page Rank :"</span>)</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> node, pagerank_preprocessing <span class="kw">in</span> sorted_pagerank_preprocessing:</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Node </span><span class="sc">{</span>node<span class="sc">}</span><span class="ss">: </span><span class="sc">{</span>pagerank_preprocessing<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Page Rank :
Node 0: 0.1303
Node 8: 0.1102
Node 2: 0.1003
Node 7: 0.1003
Node 1: 0.0784
Node 4: 0.0784
Node 5: 0.0766
Node 14: 0.0707
Node 3: 0.0605
Node 11: 0.0596
Node 15: 0.0418
Node 10: 0.0339
Node 6: 0.0118
Node 9: 0.0118
Node 12: 0.0118
Node 13: 0.0118
Node 16: 0.0118</code></pre>
</div>
</div>
<div class="cell" data-outputid="8a53d5aa-4d28-4b68-b8fa-e5a223517e4c" data-execution_count="25">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>ringkasan_pagerank_preprocessing <span class="op">=</span> <span class="st">""</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Tiga Node Tertinggi Page Rank Menggunakan Preprocessing:"</span>)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> node, pagerank_preprocessing <span class="kw">in</span> sorted_pagerank_preprocessing[:<span class="dv">3</span>]:</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>    top_sentence <span class="op">=</span> kalimat[node]</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>    ringkasan_pagerank_preprocessing <span class="op">+=</span> top_sentence <span class="op">+</span> <span class="st">" "</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Node </span><span class="sc">{</span>node<span class="sc">}</span><span class="ss">: Page Rank = </span><span class="sc">{</span>pagerank_preprocessing<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Kalimat: </span><span class="sc">{</span>top_sentence<span class="sc">}</span><span class="ch">\n</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Tiga Node Tertinggi Page Rank Menggunakan Preprocessing:
Node 0: Page Rank = 0.1303
Kalimat: Menteri Dalam Negeri (Mendagri) Tito Karnavian menunjuk Safrizal ZA sebagai Penjabat (Pj) Gubernur Bangka Belitung.

Node 8: Page Rank = 0.1102
Kalimat: Sementara untuk Velix, tugas keamanan di Papua Pegunungan menjadi prioritas.

Node 2: Page Rank = 0.1003
Kalimat: Pada saat bersamaan, Tito juga melantik Velix Vernando Wanggai sebagai Pj Gubernur Papua Pegunungan.
</code></pre>
</div>
</div>
</section>
<section id="eigen-vector" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="eigen-vector"><span class="header-section-number">10.3</span> Eigen Vector</h2>
<p>Dalam ringkasan dokumen, eigenvector tidak digunakan secara langsung untuk menghitung ringkasan. Namun, Anda dapat memanfaatkan konsep pengukuran penting dari eigenvector untuk memberikan bobot atau skor pada elemen-elemen dalam dokumen yang mungkin memiliki kepentingan lebih besar dalam rangka membuat ringkasan. Perhitungan eigenvector yang didapatkan dari matriks korelasi untuk menentukan bobot relatif setiap dokumen atau kata. Berikut merupakan rumus untuk menghitung nilai eigenvector. <br><br> <span class="math display">\[det(λ.I-A)\]</span><br><br></p>
<p>Keterangan = <br> det(⋅) = Merupakan fungsi determinan, yang menghasilkan nilai determinan dari suatu matriks. <br> λ = Merupakan simbol yang mewakili eigenvalue yang sedang dicari. <br> I = Merupakan matriks identitas yang sesuai dengan dimensi matriks. <br> A = Merupakan matriks yang eigenvalues-nya ingin dicari.</p>
<p>Eigen Vector Tanpa Preprocessing</p>
<div class="cell" data-outputid="f3dd26b1-be77-4b10-afd5-7a9f0d016aa5" data-execution_count="26">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>eigenvector <span class="op">=</span> nx.eigenvector_centrality(G)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>sorted_eigenvector<span class="op">=</span> <span class="bu">sorted</span>(eigenvector.items(), key<span class="op">=</span><span class="kw">lambda</span> x: x[<span class="dv">1</span>], reverse<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Eigen Vector :"</span>)</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> node, eigenvector <span class="kw">in</span> sorted_eigenvector:</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Node </span><span class="sc">{</span>node<span class="sc">}</span><span class="ss">: </span><span class="sc">{</span>eigenvector<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Eigen Vector :
Node 2: 0.4823
Node 7: 0.4823
Node 5: 0.4453
Node 0: 0.4426
Node 8: 0.3053
Node 11: 0.1398
Node 10: 0.1274
Node 14: 0.0958
Node 6: 0.0402
Node 15: 0.0276
Node 1: 0.0000
Node 4: 0.0000
Node 3: 0.0000
Node 9: 0.0000
Node 12: 0.0000
Node 13: 0.0000
Node 16: 0.0000</code></pre>
</div>
</div>
<div class="cell" data-outputid="ed0c6030-a008-43c3-bbe5-bf3857f55d47" data-execution_count="27">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>ringkasan_eigenvector <span class="op">=</span> <span class="st">""</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Tiga Node Tertinggi Eigen Vector:"</span>)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> node, eigenvector <span class="kw">in</span> sorted_eigenvector[:<span class="dv">3</span>]:</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>    top_sentence <span class="op">=</span> kalimat[node]</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>    ringkasan_eigenvector <span class="op">+=</span> top_sentence <span class="op">+</span> <span class="st">" "</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Node </span><span class="sc">{</span>node<span class="sc">}</span><span class="ss">: Page Rank = </span><span class="sc">{</span>eigenvector<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Kalimat: </span><span class="sc">{</span>top_sentence<span class="sc">}</span><span class="ch">\n</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Tiga Node Tertinggi Eigen Vector:
Node 2: Page Rank = 0.4823
Kalimat: Pada saat bersamaan, Tito juga melantik Velix Vernando Wanggai sebagai Pj Gubernur Papua Pegunungan.

Node 7: Page Rank = 0.4823
Kalimat: Eks Stafsus SBY Velix Wanggai Jadi Pj Gubernur Papua Pegunungan Dia meminta Safrizal menangani permasalahan lingkungan di Bangka Belitung.

Node 5: Page Rank = 0.4453
Kalimat: Tito meminta dua pj gubernur menangani kemiskinan ekstrem, inflasi, stunting, infrastruktur, pendidikan, dan kesehatan.
</code></pre>
</div>
</div>
<div class="cell" data-outputid="bb25036d-baa9-41a9-eeb7-d1aa26352eba" data-execution_count="28">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>eigenvector_preprocessing <span class="op">=</span> nx.eigenvector_centrality(G_preprocessing)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>sorted_eigenvector_preprocessing<span class="op">=</span> <span class="bu">sorted</span>(eigenvector_preprocessing.items(), key<span class="op">=</span><span class="kw">lambda</span> x: x[<span class="dv">1</span>], reverse<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Eigen Vector :"</span>)</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> node, eigenvector_preprocessing <span class="kw">in</span> sorted_eigenvector_preprocessing:</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Node </span><span class="sc">{</span>node<span class="sc">}</span><span class="ss">: </span><span class="sc">{</span>eigenvector_preprocessing<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Eigen Vector :
Node 2: 0.4692
Node 7: 0.4692
Node 0: 0.4619
Node 5: 0.3956
Node 8: 0.3344
Node 11: 0.1708
Node 3: 0.1427
Node 10: 0.1305
Node 14: 0.1027
Node 15: 0.0290
Node 1: 0.0000
Node 4: 0.0000
Node 6: 0.0000
Node 9: 0.0000
Node 12: 0.0000
Node 13: 0.0000
Node 16: 0.0000</code></pre>
</div>
</div>
<div class="cell" data-outputid="8b60bf8e-9a66-41c4-aa8e-5b5ab592ee6c" data-execution_count="29">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>ringkasan_eigenvector_preprocessing <span class="op">=</span> <span class="st">""</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Tiga Node Tertinggi Eigen Vector Menggunakan Preprocessing:"</span>)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> node, eigenvector_preprocessing <span class="kw">in</span> sorted_eigenvector_preprocessing[:<span class="dv">3</span>]:</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>    top_sentence <span class="op">=</span> kalimat[node]</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>    ringkasan_eigenvector_preprocessing <span class="op">+=</span> top_sentence <span class="op">+</span> <span class="st">" "</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Node </span><span class="sc">{</span>node<span class="sc">}</span><span class="ss">: Page Rank = </span><span class="sc">{</span>eigenvector_preprocessing<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Kalimat: </span><span class="sc">{</span>top_sentence<span class="sc">}</span><span class="ch">\n</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Tiga Node Tertinggi Eigen Vector Menggunakan Preprocessing:
Node 2: Page Rank = 0.4692
Kalimat: Pada saat bersamaan, Tito juga melantik Velix Vernando Wanggai sebagai Pj Gubernur Papua Pegunungan.

Node 7: Page Rank = 0.4692
Kalimat: Eks Stafsus SBY Velix Wanggai Jadi Pj Gubernur Papua Pegunungan Dia meminta Safrizal menangani permasalahan lingkungan di Bangka Belitung.

Node 0: Page Rank = 0.4619
Kalimat: Menteri Dalam Negeri (Mendagri) Tito Karnavian menunjuk Safrizal ZA sebagai Penjabat (Pj) Gubernur Bangka Belitung.
</code></pre>
</div>
</div>
</section>
</section>
<section id="evaluasi" class="level1" data-number="11">
<h1 data-number="11"><span class="header-section-number">11</span> Evaluasi</h1>
<p>ROUGE (<em>Recall-Oriented Understudy for Gisting Evaluation</em>) adalah sekelompok metrik evaluasi otomatis yang umum digunakan untuk mengukur kualitas ringkasan teks. ROUGE memiliki beberapa varian, dan di antaranya, ROUGE-1, ROUGE-2, dan ROUGE-L merupakan metrik yang sering digunakan untuk mengukur sejauh mana kedekatan ringkasan sistem dengan ringkasan referensi.</p>
<div class="cell" data-execution_count="30">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co">#referensi ringkasan yang dibuat secara manual</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>referensi <span class="op">=</span> [<span class="st">'Menteri Dalam Negeri Tito Karnavian melantik Safrizal ZA sebagai Penjabat Gubernur Bangka Belitung dan Velix Vernando Wanggai sebagai Penjabat Gubernur Papua Pegunungan.Tito menugaskan kedua penjabat gubernur untuk menangani isu kemiskinan ekstrem, inflasi, stunting, infrastruktur, pendidikan, kesehatan, serta persoalan khusus di wilayah masing-masing. Tito menitipkan persiapan Pemilu Serentak dan Pilkada Serentak 2024 kepada mereka, dengan harapan agar dapat membantu Komisi Pemilihan Umum (KPU) serta menekankan koordinasi dengan bupati dan wali kota untuk menyelesaikan naskah perjanjian hibah daerah.'</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-outputid="6d55a64b-29f9-4a14-b1b1-b8c46517604d" data-execution_count="31">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(referensi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>['Menteri Dalam Negeri Tito Karnavian melantik Safrizal ZA sebagai Penjabat Gubernur Bangka Belitung dan Velix Vernando Wanggai sebagai Penjabat Gubernur Papua Pegunungan.Tito menugaskan kedua penjabat gubernur untuk menangani isu kemiskinan ekstrem, inflasi, stunting, infrastruktur, pendidikan, kesehatan, serta persoalan khusus di wilayah masing-masing. Tito menitipkan persiapan Pemilu Serentak dan Pilkada Serentak 2024 kepada mereka, dengan harapan agar dapat membantu Komisi Pemilihan Umum (KPU) serta menekankan koordinasi dengan bupati dan wali kota untuk menyelesaikan naskah perjanjian hibah daerah.']</code></pre>
</div>
</div>
<div class="cell" data-execution_count="32">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> rouge(referensi, hasil_ringkasan):</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>    rouge <span class="op">=</span> Rouge()</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>    scores <span class="op">=</span> rouge.get_scores(hasil_ringkasan, referensi)</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span> (scores)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="closeness-centrality-1" class="level2" data-number="11.1">
<h2 data-number="11.1" class="anchored" data-anchor-id="closeness-centrality-1"><span class="header-section-number">11.1</span> Closeness Centrality</h2>
<div class="cell" data-outputid="d76690ef-f79d-46e7-e328-1f08de6dcf7b" data-execution_count="33">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>rouge(referensi[<span class="dv">0</span>], ringkasan_closeness)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[{'rouge-1': {'r': 0.3333333333333333, 'p': 0.5641025641025641, 'f': 0.41904761437823135}, 'rouge-2': {'r': 0.14864864864864866, 'p': 0.25, 'f': 0.1864406732892848}, 'rouge-l': {'r': 0.2878787878787879, 'p': 0.48717948717948717, 'f': 0.3619047572353742}}]</code></pre>
</div>
</div>
<div class="cell" data-outputid="f58243a0-ddd1-4901-fea7-4e85e0c4c2ed" data-execution_count="34">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>rouge(referensi[<span class="dv">0</span>], ringkasan_closeness_preprocessing)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[{'rouge-1': {'r': 0.22727272727272727, 'p': 0.42857142857142855, 'f': 0.2970296984413293}, 'rouge-2': {'r': 0.08108108108108109, 'p': 0.15384615384615385, 'f': 0.10619468574516426}, 'rouge-l': {'r': 0.18181818181818182, 'p': 0.34285714285714286, 'f': 0.23762375784726997}}]</code></pre>
</div>
</div>
<p>Berikut adalah hasil simpulan berdasarkan evaluasi ROUGE pada <em>Closeness Centrality</em>:</p>
<p>Berdasarkan evaluasi ROUGE <em>closeness centrality</em>, ditemukan bahwa tanpa menggunakan preprocessing, sistem ringkasan cenderung mencapai hasil yang lebih baik. Secara khusus, pada metrik ROUGE-1, sistem tanpa preprocessing memiliki recall sekitar 0.33, precision sekitar 0.56, dan F1-Score sekitar 0.42. Sebaliknya, ketika menggunakan preprocessing, nilai recall turun menjadi sekitar 0.23, precision sekitar 0.43, dan F1-Score sekitar 0.30.</p>
</section>
<section id="page-rank-1" class="level2" data-number="11.2">
<h2 data-number="11.2" class="anchored" data-anchor-id="page-rank-1"><span class="header-section-number">11.2</span> Page Rank</h2>
<div class="cell" data-outputid="22c85a46-a720-41fa-eb4e-468f270bc356" data-execution_count="35">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>rouge(referensi[<span class="dv">0</span>], ringkasan_pagerank)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[{'rouge-1': {'r': 0.4090909090909091, 'p': 0.675, 'f': 0.5094339575649698}, 'rouge-2': {'r': 0.24324324324324326, 'p': 0.4186046511627907, 'f': 0.3076923030433195}, 'rouge-l': {'r': 0.4090909090909091, 'p': 0.675, 'f': 0.5094339575649698}}]</code></pre>
</div>
</div>
<div class="cell" data-outputid="9727af77-048b-40dc-bfdb-401119b54300" data-execution_count="36">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>rouge(referensi[<span class="dv">0</span>], ringkasan_pagerank_preprocessing)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[{'rouge-1': {'r': 0.30303030303030304, 'p': 0.5714285714285714, 'f': 0.39603959943142836}, 'rouge-2': {'r': 0.17567567567567569, 'p': 0.34210526315789475, 'f': 0.23214285265943885}, 'rouge-l': {'r': 0.30303030303030304, 'p': 0.5714285714285714, 'f': 0.39603959943142836}}]</code></pre>
</div>
</div>
<p>Berdasarkan hasil evaluasi ROUGE pada <em>Page Rank</em> untuk ringkasan dengan dan tanpa preprocessing menggunakan metode <em>Page Rank</em>, dapat disimpulkan bahwa tanpa preprocessing sistem mampu mencapai hasil yang lebih baik dalam sebagian besar metrik evaluasi. Pada metrik ROUGE-1, sistem tanpa preprocessing memiliki nilai recall sekitar 0.41, precision sekitar 0.675, dan F1-Score sekitar 0.51. Sementara itu, dengan preprocessing, nilai recall turun menjadi sekitar 0.30, precision sekitar 0.571, dan F1-Score sekitar 0.40</p>
</section>
<section id="eigen-vector-1" class="level2" data-number="11.3">
<h2 data-number="11.3" class="anchored" data-anchor-id="eigen-vector-1"><span class="header-section-number">11.3</span> Eigen Vector</h2>
<div class="cell" data-outputid="e481f200-1287-4e42-86e6-741faff39517" data-execution_count="37">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>rouge(referensi[<span class="dv">0</span>], ringkasan_eigenvector)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[{'rouge-1': {'r': 0.3333333333333333, 'p': 0.5641025641025641, 'f': 0.41904761437823135}, 'rouge-2': {'r': 0.14864864864864866, 'p': 0.25, 'f': 0.1864406732892848}, 'rouge-l': {'r': 0.2878787878787879, 'p': 0.48717948717948717, 'f': 0.3619047572353742}}]</code></pre>
</div>
</div>
<div class="cell" data-outputid="efb8655e-f9fa-40d4-e912-068fe7fd606e" data-execution_count="38">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>rouge(referensi[<span class="dv">0</span>], ringkasan_eigenvector_preprocessing)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[{'rouge-1': {'r': 0.30303030303030304, 'p': 0.5405405405405406, 'f': 0.3883495099594685}, 'rouge-2': {'r': 0.17567567567567569, 'p': 0.29545454545454547, 'f': 0.22033897837403055}, 'rouge-l': {'r': 0.30303030303030304, 'p': 0.5405405405405406, 'f': 0.3883495099594685}}]</code></pre>
</div>
</div>
<p>Berdasarkan hasil evaluasi ROUGE untuk ringkasan dengan dan tanpa preprocessing menggunakan metode eigenvector centrality, dapat ditarik beberapa kesimpulan. Tanpa preprocessing, sistem cenderung mencapai hasil yang sedikit lebih baik pada sebagian besar metrik evaluasi. Pada metrik ROUGE-1, sistem tanpa preprocessing memiliki nilai recall sekitar 0.33, precision sekitar 0.56, dan F1-Score sekitar 0.42. Sementara itu, dengan preprocessing, nilai recall dan F1-Score tetap stabil, sedangkan precision mengalami penurunan menjadi sekitar 0.54.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./crawl_berita_cnn.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Crawl Berita CNN</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->



</body></html>